language: java
sudo: false

jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk14

cache:
  directories:
    - $HOME/.m2/

before_install:
  - mvn --version
  - java -version

script: "cd svg-core && mvn test -B"

deploy:
  provider: script
  script: "cp ../.travis.settings.xml $HOME/.m2/settings.xml && mvn source:jar javadoc:jar deploy"
  skip_cleanup: true # to upload artifacts created during the build
  on:
    branch: master
    jdk: openjdk8
    tags: true
