# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # test against
        # - Java 1.8 (minimum requirement)
        # - Java 9 (first version with JPMS)
        # - Java LTS versions (11, 17, ...)
        # - lastest Java version(s)
        java:
          - 1.8
          - 9
          - 11  # LTS
          - 15

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: cd svg-core && mvn test -B
