# https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # test against
        # - Java 1.8 (minimum requirement)
        # - Java 9 (first version with JPMS)
        # - Java LTS versions (11, 17, ...)
        # - lastest Java version(s)
        java:
          - 1.8
          - 9
          - 11  # LTS
          - 15

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode test
        working-directory: svg-core


  snapshot:
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      github.repository == 'JFormDesigner/svgSalamander'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Publish snapshot to oss.sonatype.org
        run: mvn --batch-mode source:jar javadoc:jar deploy
        working-directory: svg-core
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
